version: '3'

services:
  db:
    image: postgres
    container_name: qaapp_db
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data